name: 4-simpleCI-with-docker
on: [push]
jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Reposistory
        uses: actions/checkout@v2
      - name: Create Docker
        run: docker-compose up --build -d
      # - name: Set up Python 3.10.2
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.10.2
      # - name: Install pip
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     pip3 install django==4.0.2
      #     pip3 install gunicorn==20.1.0
      # - name: Automate test
      #   run: |
      #     python3 manage.py test
      #   working-directory: ./docs