name: 6-simpleDeploy
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clone Reposistory
        uses: actions/checkout@v2
        with: 
          clean: false
      - name: compose up
        run: sudo docker-compose up --build -d 
        working-directory: ~/project
      - name: start service
        run: sudo docker-compose exec django-4.0.2 python3 manage.py runserver 0.0.0.0:8000
        working-directory: ~/project
      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      # - name: Install pip
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     pip3 install django==4.0.2
      #     pip3 install gunicorn==20.1.0
      # - name: Automate test
      #   run: |
      #     python3 manage.py test
      #   working-directory: ./docs